/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155HashpinAdapter } from "./ERC1155HashpinAdapter";
export type { ERC721HashpinAdapter } from "./ERC721HashpinAdapter";
