/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1155HashpinAdapter__factory } from "./ERC1155HashpinAdapter__factory";
export { ERC721HashpinAdapter__factory } from "./ERC721HashpinAdapter__factory";
